let notes = JSON.parse(localStorage.getItem("exercise13Notes")) || [];
let editingNoteId = null;
let selectedNoteId = null;
let deleteMode = "single";
let messageTimer;


const noteForm = document.querySelector("#noteForm");
const formTitle = document.querySelector("#formTitle");
const titleInput = document.querySelector("#titleInput");
const categoryInput = document.querySelector("#categoryInput");
const contentInput = document.querySelector("#contentInput");
const titleError = document.querySelector("#titleError");
const categoryError = document.querySelector("#categoryError");
const contentError = document.querySelector("#contentError");
const characterCount = document.querySelector("#characterCount");
const saveButton = document.querySelector("#saveButton");
const cancelButton = document.querySelector("#cancelButton");
const clearAllButton = document.querySelector("#clearAllButton");
const searchInput = document.querySelector("#searchInput");
const filterCategory = document.querySelector("#filterCategory");
const sortNotes = document.querySelector("#sortNotes");
const notesList = document.querySelector("#notesList");
const emptyState = document.querySelector("#emptyState");
const resultText = document.querySelector("#resultText");
const totalNotes = document.querySelector("#totalNotes");
const pinnedNotes = document.querySelector("#pinnedNotes");
const importantNotes = document.querySelector("#importantNotes");
const messageBox = document.querySelector("#messageBox");
const messageText = document.querySelector("#messageText");
const closeMessageButton = document.querySelector("#closeMessageButton");
const confirmModal = document.querySelector("#confirmModal");
const modalTitle = document.querySelector("#modalTitle");
const modalMessage = document.querySelector("#modalMessage");
const cancelDeleteButton = document.querySelector("#cancelDeleteButton");
const confirmDeleteButton = document.querySelector("#confirmDeleteButton");
